### ISSUE TITLE
 an error message

### ISSUE THREAD

**Issue by Giwayla** [eXtremal-ik7/poolfrontend#2]
I don't know what is this, but I try to complie, and found below error, How to fix it?

~/Downloads/poolfrontend-master/src/http.cpp: In member function ‘void PoolHttpConnection::queryStatsHistory(StatisticDb*, const string&, const string&, int64_t, int64_t, int64_t, int64_t)’:
~/Downloads/poolfrontend-master/src/http.cpp:1024:14: error: ‘class StatisticDb’ has no member named ‘queryStatsHistory’; did you mean ‘using QueryStatsHistoryCallback = class std::function<void(const std::vector<StatisticDb::CStats>&)>’? (not accessible from this context)
 1024 |   statistic->queryStatsHistory(login, worker, timeFrom, timeTo, groupByInterval, [this, statistic, currentTime](const std::vector<StatisticDb::CStats> &stats) {
      |              ^~~~~~~~~~~~~~~~~
In file included from ~/Downloads/poolfrontend-master/src/../dependencies/poolcore/src/include/poolcore/accounting.h:6,
                 from ~/Downloads/poolfrontend-master/src/../dependencies/poolcore/src/include/poolcore/backend.h:4,
                 from ~/Downloads/poolfrontend-master/src/http.h:4,
                 from ~/Downloads/poolfrontend-master/src/http.cpp:1:
~/Downloads/poolfrontend-master/src/../dependencies/poolcore/src/include/poolcore/statistics.h:87:9: note: declared private here
   87 |   using QueryStatsHistoryCallback = std::function<void(const std::vector<StatisticDb::CStats>&)>;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/poolfrontend.dir/build.make:105: recipe for target 'CMakeFiles/poolfrontend.dir/http.cpp.o' failed
make[2]: *** [CMakeFiles/poolfrontend.dir/http.cpp.o] Error 1
CMakeFiles/Makefile2:485: recipe for target 'CMakeFiles/poolfrontend.dir/all' failed
make[1]: *** [CMakeFiles/poolfrontend.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eXtremal-ik7** [comment]
Fixed
https://github.com/eXtremal-ik7/poolfrontend/commit/2f483d170d4347c817edd88c65160321e931c76f
