### ISSUE TITLE
Got the error message with DTC miner

### ISSUE THREAD

**Issue by Giwayla** [eXtremal-ik7/poolfrontend#4]
message from server: unknow user D5pVJR6m2wSCW2Tq4X18NHGRWKPQWQ2u4s
and then reconnect to the server.
how to fix it?

**Comment by eXtremal-ik7** [comment]
Use user name in miner config instead of address

**Comment by Giwayla** [comment]
Thanks, It work when I create the user by using this command "curl -X POST -d '{"login": "user", "password": "12345678", "email": "my@email.com"}' http://localhost:18880/api/userCreate" 
But  after about 12 hours this user expires. 
How to create permanent users?

**Comment by eXtremal-ik7** [comment]
Use https://github.com/eXtremal-ik7/poolfrontend/blob/master/doc/httpApi.md#useraction for activate user. Pool send activation token to email and also write it to log.

**Comment by Giwayla** [comment]
Got it, Thank you very much
